version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - mongo-data-app:/data/db
volumes:
  mongo-data-app:
